rar a rwkvfusion_v12.rar \
visualized_img/RWKVFusion_v12_RWKVFusion/mefb_10_30 \
visualized_img/RWKVFusion_v12_RWKVFusion/mff_whu_11_9 \
visualized_img/RWKVFusion_v12_RWKVFusion/msrs_11_8 \
visualized_img/RWKVFusion_v12_RWKVFusion/realmff_11_9 \
visualized_img/RWKVFusion_v12_RWKVFusion/roadscene_11_8 \
visualized_img/RWKVFusion_v12_RWKVFusion/sice_11_1 \
visualized_img/RWKVFusion_v12_RWKVFusion/tno_11_8 \
visualized_img/RWKVFusion_v12_RWKVFusion/lytro_11_9 \
visualized_img/RWKVFusion_v12_RWKVFusion/med_harvard_11_10