python -u -m accelerate.commands.launch \
--gpu_ids "1" downstreams/segmentation/mask2former/mask2former_inference.py \
--finetune-dir="/Data3/cao/ZiHanCao/exps/panformer/downstreams/segmentation/runs" \
--dataset-name="msrs" \
--method-name="vi" \
--img-ext="jpg" \
--fused-dir="/Data3/cao/ZiHanCao/exps/panformer/visualized_img/panRWKV_v3/msrs" \
--vi-dir="/Data3/cao/ZiHanCao/datasets/MSRS/test/vi" \
--ir-dir="/Data3/cao/ZiHanCao/datasets/MSRS/test/ir" \
--mask-dir="/Data3/cao/ZiHanCao/datasets/MSRS/test/Segmentation_labels" \
--id2label-path="/Data3/cao/ZiHanCao/datasets/MSRS/MSRS-id2label.json" \
-bs 28