# MHIIF_J2 + Hermite RBF Configuration
# 基于原始MHIIF_J2架构集成Hermite RBF的配置

model:
  type: "MHIIF_J2_Hermite"
  
  # 基础MHIIF参数
  hsi_dim: 31               # 高光谱通道数
  msi_dim: 3                # 多光谱通道数
  feat_dim: 128             # HSI特征维度
  guide_dim: 128            # MSI引导特征维度
  spa_edsr_num: 3           # 空间EDSR模块数量
  spe_edsr_num: 3           # 光谱EDSR模块数量
  mlp_dim: [256, 128]       # MLP隐藏层维度
  scale: 4                  # 上采样倍数
  patch_merge: true         # 是否使用patch merge
  
  # Hermite RBF 参数
  use_hermite_rbf: true     # 是否启用Hermite RBF
  hermite_order: 2          # Hermite阶数 (0-2)
  n_kernel: 256             # RBF核心数量
  rbf_hidden_dim: 64        # RBF隐藏层维度
  hermite_weight: 0.5       # Hermite RBF输出权重 (0-1)

training:
  # 优化器参数
  optimizer: "AdamW"
  learning_rate: 2.0e-4
  weight_decay: 1.0e-4
  
  # 学习率调度
  scheduler: "CosineAnnealingLR"
  T_max: 500
  eta_min: 1.0e-6
  
  # 训练参数
  batch_size: 4
  num_epochs: 500
  gradient_clip: 1.0
  
  # Hermite损失权重
  hermite_loss_weight: 0.1  # Hermite损失相对于基础损失的权重
  
  # 核心修剪（可选）
  kernel_pruning:
    enabled: true
    threshold: 1.0e-6
    prune_epochs: [100, 200, 300]

dataset:
  name: "CAVE"
  data_path: "/path/to/cave/dataset"
  
  # 数据增强
  augmentation:
    horizontal_flip: true
    vertical_flip: true
    rotation: false
    
  # 数据加载
  num_workers: 4
  pin_memory: true

evaluation:
  # 评估指标
  metrics: ["PSNR", "SSIM", "SAM", "ERGAS", "CC"]
  
  # 评估频率
  eval_frequency: 10
  
  # 保存设置
  save_best: true
  save_frequency: 50

logging:
  # 日志设置
  log_level: "INFO"
  log_frequency: 1
  
  # RBF监控
  log_rbf_info: true        # 是否记录RBF信息
  log_rbf_frequency: 20     # RBF信息记录频率
  
  # 实验跟踪
  use_wandb: false
  use_tensorboard: true

# 实验配置
experiment:
  name: "MHIIF_J2_HermiteRBF_CAVE_x4"
  description: "MHIIF_J2集成Hermite RBF用于高光谱图像超分辨率"
  tags: ["mhiif_j2", "hermite_rbf", "hyperspectral", "super_resolution"]
  
  # 输出路径
  output_dir: "./experiments/mhiif_j2_hermite"
  checkpoint_dir: "./checkpoints/mhiif_j2_hermite"
  
  # 随机种子
  seed: 42

# 设备配置
device:
  type: "cuda"
  gpu_ids: [0]
  mixed_precision: true

# 消融实验配置（可选）
ablation:
  # 不同Hermite阶数的对比
  hermite_orders: [0, 1, 2]
  
  # 不同核心数量的对比
  kernel_counts: [128, 256, 512]
  
  # 不同权重的对比
  hermite_weights: [0.3, 0.5, 0.7]
