optimizer:
  name: 'adamw'
  lr: !!float 2e-4
  weight_decay: 0.0

lr_scheduler:
  name: 'cos_anneal'
  T_max: 300
  eta_min: !!float 1e-5

max_norm: 1e-4
ema_decay: 0.995
ema_update_every: 1

path:
  wv3_train_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/training_wv3/train_wv3.h5"
  wv3_val_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5"
  wv3_full_path: "/data2/users/yujieliang/dataset/pansharpening/pansharpening_test/test_wv3_OrigScale_multiExm1.h5"
  wv3_txt_train_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/training_wv3/t5_feature_wv3_train.safetensors"
  wv3_txt_val_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/reduced_examples/t5_feature_wv3_test_reduced.safetensors"
  wv3_txt_full_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/full_examples/t5_feature_wv3_test_full.safetensors"

  gf2_train_path: "/data2/users/yujieliang/dataset/pansharpening/gf/training_gf2/train_gf2.h5"
  gf2_val_path: "/data2/users/yujieliang/dataset/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5"
  gf2_full_path: "/data2/users/yujieliang/dataset/pansharpening/pansharpening_test/test_gf2_OrigScale_multiExm1.h5"
  gf2_txt_train_path: "/data2/users/yujieliang/dataset/pansharpening/gf/training_gf2/t5_feature_gf2_train.safetensors"
  gf2_txt_val_path: "/data2/users/yujieliang/dataset/pansharpening/gf/reduced_examples/t5_feature_gf2_reduced.safetensors"
  gf2_txt_full_path: "/data2/users/yujieliang/dataset/pansharpening/gf/full_examples/t5_feature_gf2_full.safetensors"

  qb_train_path: "/data2/users/yujieliang/dataset/pansharpening/qb/training_qb/train_qb.h5"
  qb_val_path: "/data2/users/yujieliang/dataset/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5"
  qb_full_path: "/data2/users/yujieliang/dataset/pansharpening/pansharpening_test/test_qb_OrigScale_multiExm1.h5"
  qb_txt_train_path: "/data2/users/yujieliang/dataset/pansharpening/qb/training_qb/t5_feature_qb_train.safetensors"
  qb_txt_val_path: "/data2/users/yujieliang/dataset/pansharpening/qb/reduced_examples/t5_feature_qb_reduced.safetensors"
  qb_txt_full_path: "/data2/users/yujieliang/dataset/pansharpening/qb/full_examples/t5_feature_qb_full.safetensors"

  cave_x4_train_path: "/data2/users/yujieliang/dataset/HISI/new_cave/train_cave(with_up)x4.h5"
  cave_x4_val_path: "/data2/users/yujieliang/dataset/HISI/new_cave/test_cave(with_up)x4.h5"

  cave_x8_train_path: "/data2/users/yujieliang/dataset/HISI/new_cave/x8/train_cave(with_up)x8_rgb_16.h5"
  cave_x8_val_path: "/data2/users/yujieliang/dataset/HISI/new_cave/x8/test_cave(with_up)x8_rgb.h5"

  harvard_x4_train_path: "/data2/users/yujieliang/dataset/HISI/new_harvard/train_harvard(with_up)x4_rgb.h5"
  harvard_x4_val_path: "/data2/users/yujieliang/dataset/HISI/new_harvard/test_harvard(with_up)x4_rgb.h5"

  harvard_x8_train_path: "/data2/users/yujieliang/dataset/HISI/new_harvard/x8/train_harvard(with_up)x8_rgb.h5"
  harvard_x8_val_path: "/data2/users/yujieliang/dataset/HISI/new_harvard/x8/test_harvard(with_up)x8_rgb.h5"
  
  pavia_train_path: "/data2/users/yujieliang/dataset/HISI/data_Pavia/Train_Pavia.h5"
  pavia_val_path: "/data2/users/yujieliang/dataset/HISI/data_Pavia/Test_Pavia.h5"
  pavia_txt_train_path: "/data2/users/yujieliang/dataset/HISI/data_Pavia/t5_feature_pavia_train.safetensors"
  pavia_txt_val_path: "/data2/users/yujieliang/dataset/HISI/data_Pavia/t5_feature_pavia_test.safetensors"

  chikusei_train_path: "/data2/users/yujieliang/dataset/HISI/Chikusei_x4/train_Chikusei.h5"
  chikusei_val_path: "/data2/users/yujieliang/dataset/HISI/Chikusei_x4/test_Chikusei.h5"
  chikusei_txt_train_path: "/data2/users/yujieliang/dataset/HISI/Chikusei_x4/t5_feature_chikusei_train.safetensors"
  chikusei_txt_val_path: "/data2/users/yujieliang/dataset/HISI/Chikusei_x4/t5_feature_chikusei_test.safetensors"

  msrs_base_dir: "/data2/users/yujieliang/dataset/VIF-MSRS"
  llvip_base_dir: "/data2/users/yujieliang/dataset/VIF-LLVIP/data"  # the mask is generated by using Ground-DINO-SAM project
  tno_base_dir: "/data2/users/yujieliang/dataset/VIF-TNO"
  roadscene_base_dir: "/data2/users/yujieliang/dataset/VIF-RoadSceneFusion"
  roadscene_tno_joint_base_dir: "/data2/users/yujieliang/dataset/VIF-RoadScene_and_TNO"
  m3fd_base_dir: "/data2/users/yujieliang/dataset/VIF-M3FD"
  med_harvard_base_dir: "/data2/users/yujieliang/dataset/MedHarvard"
  sice_base_dir: "/data2/users/yujieliang/dataset/MEF-SICE"
  mefb_base_dir: "/data2/users/yujieliang/dataset/MEF-MEFB"
  realmff_base_dir: "/data2/users/yujieliang/dataset/MFF-RealMFF"
  mff_whu_base_dir: "/data2/users/yujieliang/dataset/MFF-WHU/MFI-WHU"
  lytro_base_dir: "/data2/users/yujieliang/dataset/MFF-Lytro"
  vis_ir_joint_base_dir:
    # llvip: "/data2/users/yujieliang/dataset/VIF-LLVIP/data"
    # m3fd: "/data2/users/yujieliang/dataset/VIF-M3FD"
    msrs: "/data2/users/yujieliang/dataset/VIF-MSRS"
    roadscene_tno_joint: "/data2/users/yujieliang/dataset/VIF-RoadScene_and_TNO"

network_configs:
  MHIIF_MHIIF_:
  ##################### Pansharpening #####################
    ## CAVE
    hsi_dim: 31
    msi_dim: 3
    feat_dim: 128
    guide_dim: 128
    spa_edsr_num: 3
    spe_edsr_num: 3
    mlp_dim: [256,128]
    scale: 4
    patch_merge: yes
  MHIIF_g_MHIIF_g:
  ##################### Pansharpening #####################
    ## CAVE
    hsi_dim: 31
    msi_dim: 3
    feat_dim: 64
    guide_dim: 64
    sample_type: "vmap"
    spa_edsr_num: 3
    spe_edsr_num: 3
    mlp_dim: [256,128]
    scale: 4
    patch_merge: yes
    
  MHIIF_J_MHIIF_J:
    hsi_dim: 31
    msi_dim: 3
    feat_dim: 128
    guide_dim: 128 
    spa_edsr_num: 3 
    spe_edsr_num: 3
    mlp_dim: [256, 128] 
    scale: 4
    patch_merge: yes


  MHIIF_J2_MHIIF_J2:
    hsi_dim: 31
    msi_dim: 3
    feat_dim: 64
    guide_dim: 64 
    spa_edsr_num: 3 
    spe_edsr_num: 3
    mlp_dim: [256, 128] 
    scale: 4
    patch_merge: yes
      # Hermite RBF 参数
    use_hermite_rbf: true     # 是否启用Hermite RBF
    hermite_order: 2          # Hermite阶数 (0-2)
    n_kernel: 256             # RBF核心数量
    rbf_hidden_dim: 64        # RBF隐藏层维度
    hermite_weight: 1       # Hermite RBF输出权重 (0-1)


  MHIIF_gridhermit_MHIIF_gridhermit:
      hsi_dim: 31
      msi_dim: 3
      feat_dim: 64
      guide_dim: 64 
      spa_edsr_num: 3 
      spe_edsr_num: 3
      mlp_dim: [256, 128] 
      scale: 4
      patch_merge: yes



  hermite_hermite:
  ##################### Pansharpening #####################
    ## CAVE
    hsi_dim: 31
    msi_dim: 3
    feat_dim: 64
    guide_dim: 64
    spa_edsr_num: 3
    spe_edsr_num: 3
    mlp_dim: [256,128]
    scale: 4
    patch_merge: yes


  hermite_rbf_hermite_rbf:
  ##################### Pansharpening #####################
      ## CAVE
        # 基础参数
    hsi_channels: 31          # 高光谱通道数
    msi_channels: 3           # 多光谱通道数  
    scale_factor: 4           # 上采样倍数
    
    # Hermite RBF 参数
    hermite_order: 2          # Hermite阶数 (0: 仅函数值, 1: +一阶导数, 2: +二阶导数)
    n_kernel: 512             # RBF核心数量
    adaptive_sigma: true      # 是否使用自适应sigma
    rbf_type: "hermite_gauss" # RBF类型
    
    # 坐标编码参数（可选）
    use_hash_encoding: false  # 是否使用位置编码（简化版本）
    hash_levels: 16           # 编码层级数
    hash_features: 2          # 每层特征数
    
    # 网络结构参数
    # hidden_dim: 128           # 隐藏层维度
    # n_layers: 4               # 网络层数
    # hsi_dim: 31
    # msi_dim: 3
    # feat_dim: 64
    # guide_dim: 64
    # spa_edsr_num: 3
    # spe_edsr_num: 3
    # mlp_dim: [256,128]
    # scale: 4
    patch_merge: yes

  ########################## MEF ##########################
    # img_channel: 1
    # modal_channel: 1
    # mask_channel: 1
    # llm_channel: 512
    # multi_value_mask_max_classes: 20
    # out_channel: 1
    # width: 32
    # middle_blk_num: 1
    # enc_blk_nums: [1, 1]
    # dec_blk_nums: [1, 1]
    # chan_upscales: [1, 1]
    # mid_window_size: 0
    # enc_window_sizes: [0,0]
    # dec_window_sizes: [0,0]
    # ffn_hidden_rates: [2, 2]
    # MIFM_img_downsample_ratios: [8, 8]
    # pt_img_size: 256
    # drop_path_rate: 0.2
    # drop_txt_ratio: 0.0
    # txt_embd_drop_ratio: 0.0
    # if_abs_pos: no
    # upscale: 1
    # with_checkpoint: yes
    # add_multi_modal_tokens: no
    # end_proj_type: 3conv
    # reconstruction_head: fusion  # [sr, fusion]
    # fusion_prior: mean
    # scan_mode: K2   # [K2] may be good
    # shift_type: none
    # layer_resi_connection: 1conv

loss_cfg:
  l1ssim:
    weighted_r: [1.0, 0.1]
    implem_by: torch
    window_size: 5
    grad_norm: no
  hermite:
    lambda_grad: 0.05
    lambda_smooth: 0.01
    lambda_sparsity: 0.001


metric_name_for_save:
  sharpening: PSNR  # [Pansharpening: SAM, HMIF: PSNR]
  
  check_order:
    fusion: down
    sharpening: up

logger_config:
  base_path: ./log_file/
  name: MHIIF
  file_mode: w