optimizer:
  name: 'adamw'
  lr: !!float 2e-4
  weight_decay: 0.0

lr_scheduler:
  name: 'cos_anneal'
  T_max: 300
  eta_min: !!float 1e-5

max_norm: 1e-4
ema_decay: 0.995
ema_update_every: 1

path:
  cave_mulit_x4_train_path: "data/ASSR/CAVE/CAVE_train_patches_stride32_size128.h5"
  cave_mulit_x4_val_path: "data/ASSR/CAVE/CAVE_test_fullsize.h5"
  cave_mulit_x8_train_path: "data/ASSR/CAVE/CAVE_train_patches_stride32_size128.h5"
  cave_mulit_x8_val_path: "data/ASSR/CAVE/CAVE_test_fullsize.h5"
  cave_mulit_x16_train_path: "data/ASSR/CAVE/CAVE_train_patches_stride32_size128.h5"
  cave_mulit_x16_val_path: "data/ASSR/CAVE/CAVE_test_fullsize.h5"
  cave_mulit_x32_train_path: "data/ASSR/CAVE/CAVE_train_patches_stride32_size128.h5"
  cave_mulit_x32_val_path: "data/ASSR/CAVE/CAVE_test_fullsize.h5"

  harvard_mulit_x4_train_path: "data/ASSR/Harvard/Harvard_train_patches_stride128_size128.h5"
  harvard_mulit_x4_val_path: "data/ASSR/Harvard/Harvard_test_crop1024.h5"
  harvard_mulit_x8_train_path: "data/ASSR/Harvard/Harvard_train_patches_stride128_size128.h5"
  harvard_mulit_x8_val_path: "data/ASSR/Harvard/Harvard_test_crop1024.h5"
  harvard_mulit_x16_train_path: "data/ASSR/Harvard/Harvard_train_patches_stride128_size128.h5"
  harvard_mulit_x16_val_path: "data/ASSR/Harvard/Harvard_test_crop1024.h5"
  harvard_mulit_x32_train_path: "data/ASSR/Harvard/Harvard_train_patches_stride128_size128.h5"
  harvard_mulit_x32_val_path: "data/ASSR/Harvard/Harvard_test_crop1024.h5"

  paviau_mulit_x4_train_path: "data/ASSR/PaviaU/datasets/PaviaU_train_patches_stride16_size128.h5"
  paviau_mulit_x4_val_path: "data/ASSR/PaviaU/datasets/PaviaU_test_crop256x512_patch256.h5"
  paviau_mulit_x8_train_path: "data/ASSR/PaviaU/datasets/PaviaU_train_patches_stride16_size128.h5"
  paviau_mulit_x8_val_path: "data/ASSR/PaviaU/datasets/PaviaU_test_crop256x512_patch256.h5"
  paviau_mulit_x16_train_path: "data/ASSR/PaviaU/datasets/PaviaU_train_patches_stride16_size128.h5"
  paviau_mulit_x16_val_path: "data/ASSR/PaviaU/datasets/PaviaU_test_crop256x512_patch256.h5"
  paviau_mulit_x32_train_path: "data/ASSR/PaviaU/datasets/PaviaU_train_patches_stride16_size128.h5"
  paviau_mulit_x32_val_path: "data/ASSR/PaviaU/datasets/PaviaU_test_crop256x512_patch256.h5"


  paviac_mulit_x4_train_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_train_patches_stride16_size128.h5"
  paviac_mulit_x4_val_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_test_crop512x1024_patch512.h5"
  paviac_mulit_x8_train_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_train_patches_stride16_size128.h5"
  paviac_mulit_x8_val_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_test_crop512x1024_patch512.h5"
  paviac_mulit_x16_train_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_train_patches_stride16_size128.h5"
  paviac_mulit_x16_val_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_test_crop512x1024_patch512.h5"
  paviac_mulit_x32_train_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_train_patches_stride16_size128.h5"
  paviac_mulit_x32_val_path: "data/ASSR/PaviaCenter/datasets/PaviaCenter_test_crop512x1024_patch512.h5"

  chikusei_mulit_x4_train_path: "data/ASSR/Chikusei/Chikusei_train_patches_stride32_size128.h5"
  chikusei_mulit_x4_val_path: "data/ASSR/Chikusei/Chikusei_test_patches.h5"
  chikusei_mulit_x8_train_path: "data/ASSR/Chikusei/Chikusei_train_patches_stride32_size128.h5"
  chikusei_mulit_x8_val_path: "data/ASSR/Chikusei/Chikusei_test_patches.h5"
  chikusei_mulit_x16_train_path: "data/ASSR/Chikusei/Chikusei_train_patches_stride32_size128.h5"
  chikusei_mulit_x16_val_path: "data/ASSR/Chikusei/Chikusei_test_patches.h5"
  chikusei_mulit_x32_train_path: "data/ASSR/Chikusei/Chikusei_train_patches_stride32_size128.h5"
  chikusei_mulit_x32_val_path: "data/ASSR/Chikusei/Chikusei_test_patches.h5"

  botswana_mulit_x4_train_path: "data/ASSR/Botswana/datasets/Botswana_train_patches_stride16_size128.h5"
  botswana_mulit_x4_val_path: "data/ASSR/Botswana/datasets/Botswana_test_crop256x1280_patch256.h5"
  botswana_mulit_x8_train_path: "data/ASSR/Botswana/datasets/Botswana_train_patches_stride16_size128.h5"
  botswana_mulit_x8_val_path: "data/ASSR/Botswana/datasets/Botswana_test_crop256x1280_patch256.h5"
  botswana_mulit_x16_train_path: "data/ASSR/Botswana/datasets/Botswana_train_patches_stride16_size128.h5"
  botswana_mulit_x16_val_path: "data/ASSR/Botswana/datasets/Botswana_test_crop256x1280_patch256.h5"
  botswana_mulit_x32_train_path: "data/ASSR/Botswana/datasets/Botswana_train_patches_stride16_size128.h5"
  botswana_mulit_x32_val_path: "data/ASSR/Botswana/datasets/Botswana_test_crop256x1280_patch256.h5"

  wv3_train_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/training_wv3/train_wv3.h5"
  wv3_val_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5"
  wv3_full_path: "/data2/users/yujieliang/dataset/pansharpening/pansharpening_test/test_wv3_OrigScale_multiExm1.h5"
  wv3_txt_train_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/training_wv3/t5_feature_wv3_train.safetensors"
  wv3_txt_val_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/reduced_examples/t5_feature_wv3_test_reduced.safetensors"
  wv3_txt_full_path: "/data2/users/yujieliang/dataset/pansharpening/wv3/full_examples/t5_feature_wv3_test_full.safetensors"

  gf2_train_path: "/data2/users/yujieliang/dataset/pansharpening/gf/training_gf2/train_gf2.h5"
  gf2_val_path: "/data2/users/yujieliang/dataset/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5"
  gf2_full_path: "/data2/users/yujieliang/dataset/pansharpening/pansharpening_test/test_gf2_OrigScale_multiExm1.h5"
  gf2_txt_train_path: "/data2/users/yujieliang/dataset/pansharpening/gf/training_gf2/t5_feature_gf2_train.safetensors"
  gf2_txt_val_path: "/data2/users/yujieliang/dataset/pansharpening/gf/reduced_examples/t5_feature_gf2_reduced.safetensors"
  gf2_txt_full_path: "/data2/users/yujieliang/dataset/pansharpening/gf/full_examples/t5_feature_gf2_full.safetensors"

  qb_train_path: "/data2/users/yujieliang/dataset/pansharpening/qb/training_qb/train_qb.h5"
  qb_val_path: "/data2/users/yujieliang/dataset/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5"
  qb_full_path: "/data2/users/yujieliang/dataset/pansharpening/pansharpening_test/test_qb_OrigScale_multiExm1.h5"
  qb_txt_train_path: "/data2/users/yujieliang/dataset/pansharpening/qb/training_qb/t5_feature_qb_train.safetensors"
  qb_txt_val_path: "/data2/users/yujieliang/dataset/pansharpening/qb/reduced_examples/t5_feature_qb_reduced.safetensors"
  qb_txt_full_path: "/data2/users/yujieliang/dataset/pansharpening/qb/full_examples/t5_feature_qb_full.safetensors"

  cave_x4_train_path: "data/new_cave/train_cave(with_up)x4.h5"
  cave_x4_val_path: "data/new_cave/test_cave(with_up)x4.h5"

  cave_x8_train_path: "data/new_cave/x8/train_cave(with_up)x8_rgb_16.h5"
  cave_x8_val_path: "data/new_cave/x8/test_cave(with_up)x8_rgb.h5"

  harvard_x4_train_path: "data/new_harvard/train_harvard(with_up)x4_rgb.h5"
  harvard_x4_val_path: "data/new_harvard/test_harvard(with_up)x4_rgb.h5"

  harvard_x8_train_path: "data/new_harvard/x8/train_harvard(with_up)x8_rgb.h5"
  harvard_x8_val_path: "data/new_harvard/x8/test_harvard(with_up)x8_rgb.h5"
  
  pavia_train_path: "data/data_Pavia/Train_Pavia.h5"
  pavia_val_path: "data/data_Pavia/Test_Pavia.h5"
  pavia_txt_train_path: "data/data_Pavia/t5_feature_pavia_train.safetensors"
  pavia_txt_val_path: "data/data_Pavia/t5_feature_pavia_test.safetensors"

  chikusei_train_path: "data/Chikusei_x4/train_Chikusei.h5"
  chikusei_val_path: "data/Chikusei_x4/test_Chikusei.h5"
  chikusei_txt_train_path: "data/Chikusei_x4/t5_feature_chikusei_train.safetensors"
  chikusei_txt_val_path: "data/Chikusei_x4/t5_feature_chikusei_test.safetensors"

  msrs_base_dir: "/data2/users/yujieliang/dataset/VIF-MSRS"
  llvip_base_dir: "/data2/users/yujieliang/dataset/VIF-LLVIP/data"  # the mask is generated by using Ground-DINO-SAM project
  tno_base_dir: "/data2/users/yujieliang/dataset/VIF-TNO"
  roadscene_base_dir: "/data2/users/yujieliang/dataset/VIF-RoadSceneFusion"
  roadscene_tno_joint_base_dir: "/data2/users/yujieliang/dataset/VIF-RoadScene_and_TNO"
  m3fd_base_dir: "/data2/users/yujieliang/dataset/VIF-M3FD"
  med_harvard_base_dir: "/data2/users/yujieliang/dataset/MedHarvard"
  sice_base_dir: "/data2/users/yujieliang/dataset/MEF-SICE"
  mefb_base_dir: "/data2/users/yujieliang/dataset/MEF-MEFB"
  realmff_base_dir: "/data2/users/yujieliang/dataset/MFF-RealMFF"
  mff_whu_base_dir: "/data2/users/yujieliang/dataset/MFF-WHU/MFI-WHU"
  lytro_base_dir: "/data2/users/yujieliang/dataset/MFF-Lytro"
  vis_ir_joint_base_dir:
    # llvip: "/data2/users/yujieliang/dataset/VIF-LLVIP/data"
    # m3fd: "/data2/users/yujieliang/dataset/VIF-M3FD"
    msrs: "/data2/users/yujieliang/dataset/VIF-MSRS"
    roadscene_tno_joint: "/data2/users/yujieliang/dataset/VIF-RoadScene_and_TNO"

network_configs:
  MIMO_SST_Net: 
    in_chan: 102


loss_cfg:
  l1ssim:
    weighted_r: [1.0, 0.1]
    implem_by: torch
    window_size: 5
    grad_norm: no
  hermite:
    lambda_grad: 0.05
    lambda_smooth: 0.01
    lambda_sparsity: 0.001


metric_name_for_save:
  sharpening: PSNR  # [Pansharpening: SAM, HMIF: PSNR]
  
  check_order:
    fusion: down
    sharpening: up

logger_config:
  base_path: ./log_file/
  name: MIMO_SST
  file_mode: w