optimizer:
  name: "soap_precond_palm"
  lr: 3.0e-3
  weight_decay: 1.0e-6
  # betas: [0.95, 0.99]

lr_scheduler:
  name: 'cos_anneal_restart_reduce'
  T_0: 20
  T_mult: 2
  lr_mult: 0.7
  eta_min: 8.0e-5
  warmup_epochs: 0


# max_norm: 0.04
ema_decay: 0.995
ema_update_every: 1

path:
  wv3_train_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/wv3/training_wv3/train_wv3.h5"
  wv3_val_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/wv3/reduced_examples/test_wv3_multiExm1.h5"
  wv3_full_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/pansharpening_test/test_wv3_OrigScale_multiExm1.h5"

  gf2_train_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/gf/training_gf2/train_gf2.h5"
  gf2_val_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/gf/reduced_examples/test_gf2_multiExm1.h5"
  gf2_full_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/pansharpening_test/test_gf2_OrigScale_multiExm1.h5"

  qb_train_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/qb/training_qb/train_qb.h5"
  qb_val_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/qb/reduced_examples/test_qb_multiExm1.h5"
  qb_full_path: "/Data3/cao/ZiHanCao/datasets/pansharpening/pansharpening_test/test_qb_OrigScale_multiExm1.h5"

network_configs:
  unfold_deq_pan_Unfolding_DEQ:
    num_spectral: 8
    num_channel: 32
    factor: 4
    lambda1: 0.1
    lambda2: 0.001
    if_deq: true
    patch_merge: true
    args:
      # Solver
      # f_solver: "fixed_point_iter"
      f_solver: "broyden"
      b_solver: "broyden"
      # b_solver: "fixed_point_iter"
      f_max_iter: 20
      b_max_iter: 20
      f_tol: 1.0e-3
      b_tol: 1.0e-6
      f_stop_mode: "abs"
      b_stop_mode: "abs"
      eval_factor: 2.0
      eval_f_max_iter: 0

      # Norm settings
      norm_type: "weight_norm"
      norm_no_scale: false
      norm_clip: false
      norm_clip_value: 1.0
      norm_target_norm: 1.0
      sn_n_power_iters: 1

      # Training settings
      core: "sliced"
      ift: false
      hook_ift: false
      n_states: 1
      indexing: []
      gamma: 0.8
      grad: [1]
      tau: 1.0
      sup_gap: -1
      sup_loc: []

      # Regularization
      jac_loss_weight: 0.0
      jac_loss_freq: 0.0
      jac_incremental: 0

      # Monitoring
      sradius_mode: false

loss_cfg:
  l1ssim:
    weighted_r: [1.0, 0.1]
    implem_by: torch
    window_size: 5
    grad_norm: no

metric_name_for_save:
  sharpening: PSNR  # [Pansharpening: SAM, HMIF: PSNR]
  
  check_order:
    fusion: down
    sharpening: up

logger_config:
  base_path: ./log_file/
  name: unfolding_deq
  file_mode: w
