encoder_cfg:
  ch: 128
  in_channels: 3
  num_res_blocks: 4
  z_channels: 18
  ch_mult: [1, 2, 2, 4]
  resolution: 256

decoder_cfg:
  ch: 128
  out_ch: 3
  num_res_blocks: 4
  z_channels: 18
  ch_mult: [1, 2, 2, 4]
  resolution: 256

vq_loss_cfg:
  disc_in_channels: 3
  disc_start: 0
  disc_weight: 0.8
  gen_loss_weight: 0.1
  lecam_loss_weight: 0.01
  codebook_weight: 0.1
  commit_weight: 0.25
  codebook_enlarge_ratio: 0
  codebook_enlarge_steps: 2000

lfq_cfg:
  dim: 18
  channel_first: true

optimizer_cfg:
  gan_opt:
    name: adamw
    lr: 8.0e-4
    betas: [0.9, 0.999]
    weight_decay: 1.0e-4
    amsgrad: true
    fused: true

  disc_opt:
    name: adamw
    lr: 8.0e-4
    betas: [0.9, 0.999]
    weight_decay: 1.0e-4
    amsgrad: true
    fused: true

  gan_sched:
    name: cos_anneal_restart_reduce
    T_0: 2000
    T_mult: 2
    eta_min: 1.0e-5
    warmup_epochs: 1000  # actually, steps here

  disc_sched:
    name: cos_anneal_restart_reduce
    T_0: 2000
    T_mult: 2
    eta_min: 1.0e-5
    warmup_epochs: 1000  # actually, steps here


logger_config:
  name: vq_lfq
  base_path: log_file/
  file_mode: w
  