compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: configs/huggingface/deepspeed_ZERO2_bf16_config.json
distributed_type: NO # DEEPSPEED # MULTI_GPU
machine_rank: null
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 1